---

  # [en_US] Time intervals configuration
  #
  # [pt_BR] Configurações de intervalos de tempo
  #
  time_intervals:
    # [en_US] Time interval for check if there are available heroes to work
    # Default value (in minutes): 10
    #
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_to_work: 10
    
    # [en_US] Time interval to update heroes position in the map,
    # Default value (in minutes): 3
    #
    # [pt_BR] Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): 3
    refresh: 3
    
    # [en_US] Time interval to check for new maps
    # Default value (in minutes): 5 
    #
    # [pt_BR] Intervalo de tempo para verificar por novos mapas
    # Valor padrão (em segundos): 5
    check_for_new: 5

    # [en_US] Time interval to check for login request
    # Default value (in minutes): 3
    #
    # [pt_BR] Intervalo de tempo para verificar se existe solicitação de login
    # Valor padrão (em minutos): 5
    check_for_login: 5

    # [en_US] Time interval between moviments
    # Default value (in seconds): 1 
    #
    # [pt_BR] Intervalo de tempo entre movimentos
    # Valor padrão (em segundos): 1
    interval_between_moviments: 1

  # [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  #
  # [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  #
  threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    commom: 0.8

    # [en_US]
    # Default value: 0.8
    #
    # [pt_BR]
    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    go_to_work_btn: 0.9

    # [en_US]
    # Default value: 0.9
    #
    # [pt_BR]
    # Valor padrão: 0.9
    green_bar: 0.9

  resolution:
    monitors: 2
    monitor_selected: 1
  scroll:  
    # [en_US]
    # Default value: 60
    #
    # [pt_BR]
    # Valor padrão: 60
    size: 20

    # [en_US]
    # Default value: 3
    #
    # [pt_BR]
    # Valor padrão: 3
    attemps: 5

    # [en_US]
    # Default value: true
    #
    # [pt_BR]
    # Valor padrão: true
    use_click_and_drag_instead_of_scroll: true

    # [en_US]
    # Default value: 200
    #
    # [pt_BR]
    # Valor padrão: 200
    click_and_drag_amount: 100