---
  # [en_US] How confident the bot needs to be to click the buttons (values from 0 to 1. 0 is the minimum value, 1 is the maximum value)
  #
  # [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  #
  threshold:
    # [en_US]
    # Default value: 0.7
    #
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7

  timeout:
    connect_wallet: 1
    sign: 2
    send_to_fight: 0.5
    send_to_boss: 1
    surrender: 0.5
    empty_spaceships: 1

  resolution:
    monitors: 1
    monitor_selected: 1
